title: Isle of Arran Farmhouse
description: >
  A charming 3-bedroom farmhouse on the beautiful Isle of Arran in Scotland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexanders1000.github.io/arran-farmhouse" # the base hostname & protocol for your site
